name: Build on windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project on windows with qt ${{ matrix.qt }}
    runs-on: windows-latest
    strategy:
      matrix:
        qt: ['6.2.*']

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
    - name: qmake
      run: qmake
    - name: make
      run: make all
