name: Make static version on Windows CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v3
     - name: Install Qt Static   
       uses: orestonce/install-qt-static@v0.4.0
       with:
         version: "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104"
     - name: qmake release
       run: qmake config+=release
     - name: make
       run: make
     - uses: actions/upload-artifact@v3
       with:
         name: version
         path: |
           release/*.exe
           coefs
           LICENSE
           README.md
