name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project on ${{ matrix.os }} with ${{ matrix.qt }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        qt: ['6.2.*']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
    - name: qmake
      run: qmake
    - name: make
      run: make -j4 all
